from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QWidget

class analyzer(QWidget):

    def __init__(self, centralwidget):
        super().__init__(centralwidget)
        
        self.AnalysisLbl = QtWidgets.QLabel(centralwidget)
        self.AnalysisLbl.setGeometry(QtCore.QRect(730, 10, 98, 30))
        font = QtGui.QFont()
        font.setFamily(".Farah PUA")
        font.setPointSize(24)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        font.setKerning(False)
        self.AnalysisLbl.setFont(font)
        self.AnalysisLbl.setObjectName("AnalysisLbl")
        self.progressBar = QtWidgets.QProgressBar(centralwidget)
        self.progressBar.setGeometry(QtCore.QRect(770, 800, 201, 20))
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.buttonBox = QtWidgets.QDialogButtonBox(centralwidget)
        self.buttonBox.setGeometry(QtCore.QRect(790, 770, 171, 32))
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Apply|QtWidgets.QDialogButtonBox.Close)
        self.buttonBox.setObjectName("buttonBox")
        self.AnalysisMode = QtWidgets.QToolBox(centralwidget)
        self.AnalysisMode.setGeometry(QtCore.QRect(590, 50, 381, 311))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.AnalysisMode.setFont(font)
        self.AnalysisMode.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.AnalysisMode.setFrameShadow(QtWidgets.QFrame.Plain)
        self.AnalysisMode.setObjectName("AnalysisMode")
        self.NucleiDetection = QtWidgets.QWidget()
        self.NucleiDetection.setGeometry(QtCore.QRect(0, 0, 381, 171))
        self.NucleiDetection.setObjectName("NucleiDetection")
        self.NucleiChLbl = QtWidgets.QLabel(self.NucleiDetection)
        self.NucleiChLbl.setGeometry(QtCore.QRect(10, 0, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.NucleiChLbl.setFont(font)
        self.NucleiChLbl.setObjectName("NucleiChLbl")
        self.CellTypeLabel = QtWidgets.QLabel(self.NucleiDetection)
        self.CellTypeLabel.setGeometry(QtCore.QRect(10, 30, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.CellTypeLabel.setFont(font)
        self.CellTypeLabel.setObjectName("CellTypeLabel")
        self.NucDetectMethodLbl = QtWidgets.QLabel(self.NucleiDetection)
        self.NucDetectMethodLbl.setGeometry(QtCore.QRect(10, 60, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.NucDetectMethodLbl.setFont(font)
        self.NucDetectMethodLbl.setObjectName("NucDetectMethodLbl")
        self.NucleiChannel = QtWidgets.QComboBox(self.NucleiDetection)
        self.NucleiChannel.setGeometry(QtCore.QRect(80, 0, 211, 31))
        self.NucleiChannel.setObjectName("NucleiChannel")
        self.NucleiChannel.addItem("Channel 1")
        self.NucleiChannel.addItem("Channel 2")
        self.NucleiChannel.addItem("Channel 3")
        self.NucleiChannel.addItem("Channel 4")
        self.NucCellType = QtWidgets.QComboBox(self.NucleiDetection)
        self.NucCellType.setGeometry(QtCore.QRect(80, 30, 211, 31))
        self.NucCellType.setObjectName("NucCellType")
        self.NucCellType.addItem("")
        self.NucDetectMethod = QtWidgets.QComboBox(self.NucleiDetection)
        self.NucDetectMethod.setGeometry(QtCore.QRect(80, 60, 211, 31))
        self.NucDetectMethod.setObjectName("NucDetectMethod")
        self.NucDetectMethod.addItem("CNN")
        self.NucDetectMethod.addItem("ImageProc")

        
        self.NucMaxZprojectCheckBox = QtWidgets.QCheckBox(self.NucleiDetection)
        self.NucMaxZprojectCheckBox.setGeometry(QtCore.QRect(156, 130, 151, 20))
        self.NucMaxZprojectCheckBox.setObjectName("NucMaxZprojectCheckBox")
        self.ThreeDNucSeg = QtWidgets.QCheckBox(self.NucleiDetection)
        self.ThreeDNucSeg.setGeometry(QtCore.QRect(10, 130, 131, 20))
        self.ThreeDNucSeg.setObjectName("ThreeDNucSeg")
        self.AnalysisMode.addItem(self.NucleiDetection, "")
        self.CellBoundary = QtWidgets.QWidget()
        self.CellBoundary.setGeometry(QtCore.QRect(0, 0, 381, 171))
        self.CellBoundary.setObjectName("CellBoundary")
        self.CytoChLbl = QtWidgets.QLabel(self.CellBoundary)
        self.CytoChLbl.setGeometry(QtCore.QRect(20, 0, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.CytoChLbl.setFont(font)
        self.CytoChLbl.setObjectName("CytoChLbl")
        self.CytoCellTypeLbl = QtWidgets.QLabel(self.CellBoundary)
        self.CytoCellTypeLbl.setGeometry(QtCore.QRect(20, 30, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.CytoCellTypeLbl.setFont(font)
        self.CytoCellTypeLbl.setObjectName("CytoCellTypeLbl")
        self.CytoDetectMethodLbl = QtWidgets.QLabel(self.CellBoundary)
        self.CytoDetectMethodLbl.setGeometry(QtCore.QRect(20, 60, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.CytoDetectMethodLbl.setFont(font)
        self.CytoDetectMethodLbl.setObjectName("CytoDetectMethodLbl")
        
        self.CytoChannel = QtWidgets.QComboBox(self.CellBoundary)
        self.CytoChannel.setGeometry(QtCore.QRect(90, 0, 211, 31))
        self.CytoChannel.setObjectName("CytoChannel")
        self.CytoChannel.addItem("")
        self.CytoChannel.addItem("")
        self.CytoChannel.addItem("")
        self.CytoChannel.addItem("")
        self.CytoDetectMethod = QtWidgets.QComboBox(self.CellBoundary)
        self.CytoDetectMethod.setGeometry(QtCore.QRect(90, 60, 211, 31))
        self.CytoDetectMethod.setObjectName("CytoDetectMethod")
        self.CytoDetectMethod.addItem("")
        self.CytoCellType = QtWidgets.QComboBox(self.CellBoundary)
        self.CytoCellType.setGeometry(QtCore.QRect(90, 30, 211, 31))
        self.CytoCellType.setObjectName("CytoCellType")
        self.CytoCellType.addItem("")
        self.RunCytoDetection = QtWidgets.QCheckBox(self.CellBoundary)
        self.RunCytoDetection.setGeometry(QtCore.QRect(166, 140, 151, 20))
        self.RunCytoDetection.setObjectName("RunCytoDetection")
        self.ThreeDCytoSeg = QtWidgets.QCheckBox(self.CellBoundary)
        self.ThreeDCytoSeg.setGeometry(QtCore.QRect(10, 140, 131, 20))
        self.ThreeDCytoSeg.setObjectName("ThreeDCytoSeg")
        self.AnalysisMode.addItem(self.CellBoundary, "")
        self.SpotDetection = QtWidgets.QWidget()
        self.SpotDetection.setGeometry(QtCore.QRect(0, 0, 381, 171))
        self.SpotDetection.setObjectName("SpotDetection")

        self.SpotCh1CheckBox = QtWidgets.QCheckBox(self.SpotDetection)
        self.SpotCh1CheckBox.setGeometry(QtCore.QRect(10, 10, 51, 20))
        self.SpotCh1CheckBox.setObjectName("Ch1CheckBox")
        self.SpotCh1CheckBox.setStyleSheet("color: gray")
        self.SpotCh2CheckBox = QtWidgets.QCheckBox(self.SpotDetection)
        self.SpotCh2CheckBox.setGeometry(QtCore.QRect(70, 10, 51, 20))
        self.SpotCh2CheckBox.setObjectName("Ch2CheckBox")
        self.SpotCh2CheckBox.setStyleSheet("color: red")
        self.SpotCh3CheckBox = QtWidgets.QCheckBox(self.SpotDetection)
        self.SpotCh3CheckBox.setGeometry(QtCore.QRect(130, 10, 51, 20))
        self.SpotCh3CheckBox.setObjectName("Ch3CheckBox")
        self.SpotCh3CheckBox.setStyleSheet("color: green")
        self.SpotCh4CheckBox = QtWidgets.QCheckBox(self.SpotDetection)
        self.SpotCh4CheckBox.setGeometry(QtCore.QRect(190, 10, 51, 20))
        self.SpotCh4CheckBox.setObjectName("Ch4CheckBox")
        self.SpotCh4CheckBox.setStyleSheet("color: blue")
        self.SpotCh5CheckBox = QtWidgets.QCheckBox(self.SpotDetection)
        self.SpotCh5CheckBox.setGeometry(QtCore.QRect(250, 10, 51, 20))
        self.SpotCh5CheckBox.setObjectName("Ch5CheckBox")
        self.SpotCh5CheckBox.setStyleSheet("color: orange")
        
        self.SpotCoordinatesLbl = QtWidgets.QLabel(self.SpotDetection)
        self.SpotCoordinatesLbl.setGeometry(QtCore.QRect(10, 60, 85, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Coor_CenterOfMass = QtWidgets.QCheckBox(self.SpotDetection)
        self.Coor_CenterOfMass.setGeometry(QtCore.QRect(100, 40, 131, 20))
        self.Coor_CenterOfMass.setObjectName("CenterOfMass")
        self.Coor_MaxIntensity = QtWidgets.QCheckBox(self.SpotDetection)
        self.Coor_MaxIntensity.setGeometry(QtCore.QRect(100, 60, 141, 20))
        self.Coor_MaxIntensity.setObjectName("MaxIntensity")
        self.Coor_SpotCentroid = QtWidgets.QCheckBox(self.SpotDetection)
        self.Coor_SpotCentroid.setGeometry(QtCore.QRect(100, 80, 141, 20))
        self.Coor_SpotCentroid.setObjectName("Spot Cnetroid")
        
        
        
        self.ThreeDSpotDetect = QtWidgets.QCheckBox(self.SpotDetection)
        self.ThreeDSpotDetect.setGeometry(QtCore.QRect(10, 110, 111, 20))
        self.ThreeDSpotDetect.setObjectName("ThreeDSpotDetect")
        self.SpotMaxZProject = QtWidgets.QCheckBox(self.SpotDetection)
        self.SpotMaxZProject.setGeometry(QtCore.QRect(160, 110, 131, 20))
        self.SpotMaxZProject.setObjectName("SpotMaxZProject")
        self.AnalysisMode.addItem(self.SpotDetection, "")
        self.Results = QtWidgets.QWidget()
        self.Results.setGeometry(QtCore.QRect(0, 0, 381, 171))
        self.Results.setObjectName("Results")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.Results)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.NucleiArea = QtWidgets.QCheckBox(self.Results)
        self.NucleiArea.setObjectName("NucleiArea")
        self.gridLayout_3.addWidget(self.NucleiArea, 0, 0, 1, 1)
        self.SpotsDistance = QtWidgets.QCheckBox(self.Results)
        self.SpotsDistance.setObjectName("SpotsDistance")
        self.gridLayout_3.addWidget(self.SpotsDistance, 0, 1, 1, 1)
        self.checkBox_12 = QtWidgets.QCheckBox(self.Results)
        self.checkBox_12.setObjectName("checkBox_12")
        self.gridLayout_3.addWidget(self.checkBox_12, 0, 2, 1, 1)
        self.CellArea = QtWidgets.QCheckBox(self.Results)
        self.CellArea.setObjectName("CellArea")
        self.gridLayout_3.addWidget(self.CellArea, 1, 0, 1, 1)
        self.SpotPerCell = QtWidgets.QCheckBox(self.Results)
        self.SpotPerCell.setObjectName("SpotPerCell")
        self.gridLayout_3.addWidget(self.SpotPerCell, 1, 1, 1, 1)
        self.checkBox_13 = QtWidgets.QCheckBox(self.Results)
        self.checkBox_13.setObjectName("checkBox_13")
        self.gridLayout_3.addWidget(self.checkBox_13, 1, 2, 1, 1)
        self.AnalysisMode.addItem(self.Results, "")
        
        _translate = QtCore.QCoreApplication.translate
        self.AnalysisLbl.setText(_translate("MainWindow", "Analysis"))
        self.NucleiChLbl.setText(_translate("MainWindow", "Channel"))
        self.CellTypeLabel.setText(_translate("MainWindow", "Cell Type"))
        self.NucDetectMethodLbl.setText(_translate("MainWindow", "Method"))
        self.NucleiChannel.setItemText(0, _translate("MainWindow", "Channel 1"))
        self.NucleiChannel.setItemText(1, _translate("MainWindow", "Channel 2"))
        self.NucleiChannel.setItemText(2, _translate("MainWindow", "Channel 3"))
        self.NucleiChannel.setItemText(3, _translate("MainWindow", "Channel 4"))
        self.NucCellType.setItemText(0, _translate("MainWindow", "Human Cell"))
        self.NucDetectMethod.setItemText(0, _translate("MainWindow", "DL-MRCNN"))
        self.NucDetectMethod.setItemText(1, _translate("MainWindow", "Cell Specific Processing"))
        
        self.SpotCh1CheckBox.setText(_translate("MainWindow", "Ch1"))
        self.SpotCh2CheckBox.setText(_translate("MainWindow", "Ch2"))
        self.SpotCh3CheckBox.setText(_translate("MainWindow", "Ch3"))
        self.SpotCh4CheckBox.setText(_translate("MainWindow", "Ch4"))
        self.SpotCh5CheckBox.setText(_translate("MainWindow", "Ch5"))
        self.Coor_CenterOfMass.setText(_translate("MainWindow", "Center of Mass"))
        self.Coor_MaxIntensity.setText(_translate("MainWindow", "Maximum Intensity"))
        self.Coor_SpotCentroid.setText(_translate("MainWindow", "Spot Centroid"))
        self.NucMaxZprojectCheckBox.setText(_translate("MainWindow", "Max Z-projection"))
        self.ThreeDNucSeg.setText(_translate("MainWindow", "3D Segmentation"))
        self.AnalysisMode.setItemText(self.AnalysisMode.indexOf(self.NucleiDetection), _translate("MainWindow", 
                                                                                                  "Nuclei Detection"))
        self.CytoChLbl.setText(_translate("MainWindow", "Channel"))
        self.CytoCellTypeLbl.setText(_translate("MainWindow", "Cell Type"))
        self.SpotCoordinatesLbl.setText(_translate("MainWindow", "Coordinates:"))
        self.CytoDetectMethodLbl.setText(_translate("MainWindow", "Method"))
        self.CytoChannel.setItemText(0, _translate("MainWindow", "Channel 1"))
        self.CytoChannel.setItemText(1, _translate("MainWindow", "Channel 2"))
        self.CytoChannel.setItemText(2, _translate("MainWindow", "Channel 3"))
        self.CytoChannel.setItemText(3, _translate("MainWindow", "Channel 4"))
        self.CytoDetectMethod.setItemText(0, _translate("MainWindow", "Cell Specific"))
        self.CytoCellType.setItemText(0, _translate("MainWindow", "Human Cell"))
        self.RunCytoDetection.setText(_translate("MainWindow", "Add to resutls"))
        self.ThreeDCytoSeg.setText(_translate("MainWindow", "3D Segmentation"))
        self.AnalysisMode.setItemText(self.AnalysisMode.indexOf(self.CellBoundary), _translate("MainWindow", "Cell Boundary"))
        #self.SpotChLbl.setText(_translate("MainWindow", "Channel"))
        self.ThreeDSpotDetect.setText(_translate("MainWindow", "3D Detection"))
        self.SpotMaxZProject.setText(_translate("MainWindow", "Max Z-projection"))
        self.AnalysisMode.setItemText(self.AnalysisMode.indexOf(self.SpotDetection), _translate("MainWindow", "Spot Detection"))
        self.NucleiArea.setText(_translate("MainWindow", "Nuclei Mask"))
        self.SpotsDistance.setText(_translate("MainWindow", "Spots Location"))
        self.checkBox_12.setText(_translate("MainWindow", "Spots Trajectory"))
        self.CellArea.setText(_translate("MainWindow", "Cell Mask"))
        self.SpotPerCell.setText(_translate("MainWindow", "Spots association"))
        self.checkBox_13.setText(_translate("MainWindow", "Spots Intensity"))
        self.AnalysisMode.setItemText(self.AnalysisMode.indexOf(self.Results), _translate("MainWindow", "Results"))