#from controlpanel import Ui_MainWindow
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QWidget

class display(QWidget):
    photoClicked = QtCore.pyqtSignal(QtCore.QPoint)
    
    def __init__(self, centralwidget):
        super().__init__(centralwidget)
        
        self.DisplayToolbox = QtWidgets.QGroupBox(centralwidget)
        self.DisplayToolbox.setGeometry(QtCore.QRect(10, 150, 541, 641))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.DisplayToolbox.setFont(font)
        self.DisplayToolbox.setObjectName("DisplayToolbox")
        self.ColSpinBox = QtWidgets.QSpinBox(self.DisplayToolbox)
        self.ColSpinBox.setGeometry(QtCore.QRect(450, 530, 48, 21))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.ColSpinBox.setFont(font)
        self.ColSpinBox.setObjectName("ColSpinBox")
        
        self.scene = QtWidgets.QGraphicsScene()

        self.ImageView = QtWidgets.QGraphicsView(self.DisplayToolbox)
        self.ImageView.setGeometry(QtCore.QRect(30, 170, 411, 350))
        self.ImageView.setMouseTracking(True)
        self.ImageView.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.ImageView.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.ImageView.setFrameShadow(QtWidgets.QFrame.Raised)
        self.ImageView.setTransformationAnchor(QtWidgets.QGraphicsView.AnchorUnderMouse)
        self.ImageView.setResizeAnchor(QtWidgets.QGraphicsView.AnchorUnderMouse)
        self.ImageView.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.ImageView.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.ImageView.setBackgroundBrush(QtGui.QBrush(QtGui.QColor(30, 30, 30)))
        self.ImageView.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.ImageView.setDragMode(QtWidgets.QGraphicsView.ScrollHandDrag)
        self.ImageView.setObjectName("ImageDisplay")
        
        self.ApplyMaxMin = QtWidgets.QPushButton(self.DisplayToolbox)
        self.ApplyMaxMin.setGeometry(QtCore.QRect(440, 130, 71, 32))
        self.ApplyMaxMin.setObjectName("ApplyMaxMin")
        self.HistogramsView = QtWidgets.QGraphicsView(self.DisplayToolbox)
        self.HistogramsView.setGeometry(QtCore.QRect(10, 30, 231, 101))
        self.HistogramsView.setObjectName("HistogramsView")
        self.ResetHistogram = QtWidgets.QPushButton(self.DisplayToolbox)
        self.ResetHistogram.setGeometry(QtCore.QRect(370, 130, 71, 32))
        self.ResetHistogram.setObjectName("ResetHistogram")
        self.MaxHistSpinBox = QtWidgets.QSpinBox(self.DisplayToolbox)
        self.MaxHistSpinBox.setGeometry(QtCore.QRect(470, 100, 48, 24))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.MaxHistSpinBox.setFont(font)
        self.MaxHistSpinBox.setObjectName("MaxHistSpinBox")
        self.MaxHistSlider = QtWidgets.QSlider(self.DisplayToolbox)
        self.MaxHistSlider.setGeometry(QtCore.QRect(280, 100, 191, 22))
        self.MaxHistSlider.setOrientation(QtCore.Qt.Horizontal)
        self.MaxHistSlider.setObjectName("MaxHistSlider")
        self.MaxHistLbl = QtWidgets.QLabel(self.DisplayToolbox)
        self.MaxHistLbl.setGeometry(QtCore.QRect(250, 100, 31, 21))
        self.MaxHistLbl.setObjectName("MaxHistLbl")
        self.MinHistSpinBox = QtWidgets.QSpinBox(self.DisplayToolbox)
        self.MinHistSpinBox.setGeometry(QtCore.QRect(470, 70, 48, 24))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.MinHistSpinBox.setFont(font)
        self.MinHistSpinBox.setObjectName("MinHistSpinBox")
        self.MinHistLbl = QtWidgets.QLabel(self.DisplayToolbox)
        self.MinHistLbl.setGeometry(QtCore.QRect(250, 70, 31, 21))
        self.MinHistLbl.setObjectName("MinHistLbl")
        self.MinHistSlider = QtWidgets.QSlider(self.DisplayToolbox)
        self.MinHistSlider.setGeometry(QtCore.QRect(280, 70, 191, 22))
        self.MinHistSlider.setOrientation(QtCore.Qt.Horizontal)
        self.MinHistSlider.setObjectName("MinHistSlider")
        self.ColScroller = QtWidgets.QScrollBar(self.DisplayToolbox)
        self.ColScroller.setGeometry(QtCore.QRect(30, 530, 411, 16))
        self.ColScroller.setOrientation(QtCore.Qt.Horizontal)
        self.ColScroller.setObjectName("ColScroller")
        self.ZScroller = QtWidgets.QScrollBar(self.DisplayToolbox)
        self.ZScroller.setGeometry(QtCore.QRect(30, 560, 411, 16))
        self.ZScroller.setOrientation(QtCore.Qt.Horizontal)
        self.ZScroller.setObjectName("ZScroller")
        self.ZSpinBox = QtWidgets.QSpinBox(self.DisplayToolbox)
        self.ZSpinBox.setGeometry(QtCore.QRect(450, 560, 48, 21))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.ZSpinBox.setFont(font)
        self.ZSpinBox.setObjectName("ZSpinBox")
        self.TScroller = QtWidgets.QScrollBar(self.DisplayToolbox)
        self.TScroller.setGeometry(QtCore.QRect(30, 590, 411, 16))
        self.TScroller.setOrientation(QtCore.Qt.Horizontal)
        self.TScroller.setObjectName("TScroller")
        self.TSpinBox = QtWidgets.QSpinBox(self.DisplayToolbox)
        self.TSpinBox.setGeometry(QtCore.QRect(450, 590, 48, 20))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.TSpinBox.setFont(font)
        self.TSpinBox.setObjectName("TSpinBox")
        self.ColLabel = QtWidgets.QLabel(self.DisplayToolbox)
        self.ColLabel.setGeometry(QtCore.QRect(5, 530, 21, 20))
        self.ColLabel.setObjectName("ColLabel")
        self.ZLabel = QtWidgets.QLabel(self.DisplayToolbox)
        self.ZLabel.setGeometry(QtCore.QRect(10, 560, 16, 16))
        self.ZLabel.setObjectName("ZLabel")
        self.TLabel = QtWidgets.QLabel(self.DisplayToolbox)
        self.TLabel.setGeometry(QtCore.QRect(10, 590, 16, 16))
        self.TLabel.setObjectName("TLabel")
        self.RowScroller = QtWidgets.QScrollBar(self.DisplayToolbox)
        self.RowScroller.setGeometry(QtCore.QRect(10, 170, 16, 351))
        self.RowScroller.setOrientation(QtCore.Qt.Vertical)
        self.RowScroller.setObjectName("RowScroller")
        self.RowSpinBox = QtWidgets.QSpinBox(self.DisplayToolbox)
        self.RowSpinBox.setGeometry(QtCore.QRect(0, 146, 41, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.RowSpinBox.setFont(font)
        self.RowSpinBox.setObjectName("RowSpinBox")
        self.RowLabel = QtWidgets.QLabel(self.DisplayToolbox)
        self.RowLabel.setGeometry(QtCore.QRect(0, 130, 31, 21))
        self.RowLabel.setObjectName("RowLabel")
        self.HistAutoAdjust = QtWidgets.QPushButton(self.DisplayToolbox)
        self.HistAutoAdjust.setGeometry(QtCore.QRect(300, 130, 71, 32))
        self.HistAutoAdjust.setObjectName("HistAutoAdjust")
        self.Ch1CheckBox = QtWidgets.QCheckBox(self.DisplayToolbox)
        self.Ch1CheckBox.setGeometry(QtCore.QRect(450, 170, 51, 20))
        self.Ch1CheckBox.setObjectName("Ch1CheckBox")
        self.Ch1CheckBox.setStyleSheet("color: gray")
        self.Ch2CheckBox = QtWidgets.QCheckBox(self.DisplayToolbox)
        self.Ch2CheckBox.setGeometry(QtCore.QRect(450, 190, 51, 20))
        self.Ch2CheckBox.setObjectName("Ch2CheckBox")
        self.Ch2CheckBox.setStyleSheet("color: red")
        self.Ch3CheckBox = QtWidgets.QCheckBox(self.DisplayToolbox)
        self.Ch3CheckBox.setGeometry(QtCore.QRect(450, 210, 51, 20))
        self.Ch3CheckBox.setObjectName("Ch3CheckBox")
        self.Ch3CheckBox.setStyleSheet("color: green")
        self.Ch4CheckBox = QtWidgets.QCheckBox(self.DisplayToolbox)
        self.Ch4CheckBox.setGeometry(QtCore.QRect(450, 230, 51, 20))
        self.Ch4CheckBox.setObjectName("Ch4CheckBox")
        self.Ch4CheckBox.setStyleSheet("color: blue")
        self.Ch5CheckBox = QtWidgets.QCheckBox(self.DisplayToolbox)
        self.Ch5CheckBox.setGeometry(QtCore.QRect(450, 250, 51, 20))
        self.Ch5CheckBox.setObjectName("Ch5CheckBox")
        self.Ch5CheckBox.setStyleSheet("color: orange")
        
        self.HistChLabel = QtWidgets.QLabel(self.DisplayToolbox)
        self.HistChLabel.setGeometry(QtCore.QRect(250, 30, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.HistChLabel.setFont(font)
        self.HistChLabel.setObjectName("HistChLabel")
        self.HistChannel = QtWidgets.QComboBox(self.DisplayToolbox)
        self.HistChannel.setGeometry(QtCore.QRect(310, 30, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.HistChannel.setFont(font)
        self.HistChannel.setObjectName("HistChannel")
        self.HistChannel.addItem("Ch 1")
        self.HistChannel.addItem("Ch 2")
        self.HistChannel.addItem("Ch 3")
        self.HistChannel.addItem("Ch 4")
        self.FOVScroller = QtWidgets.QScrollBar(self.DisplayToolbox)
        self.FOVScroller.setGeometry(QtCore.QRect(80, 140, 141, 16))
        self.FOVScroller.setOrientation(QtCore.Qt.Horizontal)
        self.FOVScroller.setObjectName("FOVScroller")
        self.FOVSpinBox = QtWidgets.QSpinBox(self.DisplayToolbox)
        self.FOVSpinBox.setGeometry(QtCore.QRect(230, 140, 41, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.FOVSpinBox.setFont(font)
        self.FOVSpinBox.setObjectName("FOVSpinBox")
        self.FOVLabel = QtWidgets.QLabel(self.DisplayToolbox)
        self.FOVLabel.setGeometry(QtCore.QRect(50, 140, 31, 20))
        self.FOVLabel.setObjectName("FOVLabel")
        
        self.NuclMaskCheckBox = QtWidgets.QCheckBox(self.DisplayToolbox)
        self.NuclMaskCheckBox.setGeometry(QtCore.QRect(5, 615, 70, 20))
        self.NuclMaskCheckBox.setObjectName("NucMaskCheckBox")
        self.NuclMaskCheckBox.setStyleSheet("color: red")
        self.NucPreviewMethod = QtWidgets.QComboBox(self.DisplayToolbox)
        self.NucPreviewMethod.setGeometry(QtCore.QRect(75, 610, 110, 31))
        self.NucPreviewMethod.setObjectName("NucPreviewMethod")
        self.NucPreviewMethod.addItem("Boundary")
        self.NucPreviewMethod.addItem("Area")
        
        self.SpotsCheckBox = QtWidgets.QCheckBox(self.DisplayToolbox)
        self.SpotsCheckBox.setGeometry(QtCore.QRect(205, 615, 60, 20))
        self.SpotsCheckBox.setObjectName("SpotDetection")
        self.SpotsCheckBox.setStyleSheet("color: green")
        
        self.SpotPreviewMethod = QtWidgets.QComboBox(self.DisplayToolbox)
        self.SpotPreviewMethod.setGeometry(QtCore.QRect(265, 610, 80, 31))
        self.SpotPreviewMethod.setObjectName("SpotPreviewMethod")
        self.SpotPreviewMethod.addItem("Dots")
        self.SpotPreviewMethod.addItem("Cross")
        
        self.CytoPreviewCheck = QtWidgets.QCheckBox(self.DisplayToolbox)
        self.CytoPreviewCheck.setGeometry(QtCore.QRect(365, 610, 45, 31))
        self.CytoPreviewCheck.setObjectName("CytoPreviewCheck")
        self.CytoPreviewCheck.setStyleSheet("color: blue")
        
        self.CytoDisplayMethod = QtWidgets.QComboBox(self.DisplayToolbox)
        self.CytoDisplayMethod.setGeometry(QtCore.QRect(410, 610, 110, 31))
        self.CytoDisplayMethod.setObjectName("CytoDisplayMethod")
        self.CytoDisplayMethod.addItem("Boundary")
        self.CytoDisplayMethod.addItem("Area")
        
        
        _translate = QtCore.QCoreApplication.translate
        self.DisplayToolbox.setTitle(_translate("MainWindow", "Display Toolbox"))
        self.ApplyMaxMin.setText(_translate("MainWindow", "Apply"))
        self.ResetHistogram.setText(_translate("MainWindow", "Reset"))
        self.MaxHistLbl.setText(_translate("MainWindow", "Max"))
        self.MinHistLbl.setText(_translate("MainWindow", "Min"))
        self.ColLabel.setText(_translate("MainWindow", "Col"))
        self.ZLabel.setText(_translate("MainWindow", "Z"))
        self.TLabel.setText(_translate("MainWindow", "t"))
        self.RowLabel.setText(_translate("MainWindow", "Row"))
        self.HistAutoAdjust.setText(_translate("MainWindow", "Auto"))
        self.Ch1CheckBox.setText(_translate("MainWindow", "Ch1"))
        self.Ch2CheckBox.setText(_translate("MainWindow", "Ch2"))
        self.Ch3CheckBox.setText(_translate("MainWindow", "Ch3"))
        self.Ch4CheckBox.setText(_translate("MainWindow", "Ch4"))
        self.Ch5CheckBox.setText(_translate("MainWindow", "Ch5"))
        self.HistChLabel.setText(_translate("MainWindow", "Channel"))
        self.HistChannel.setItemText(0, _translate("MainWindow", "Ch 1"))
        self.HistChannel.setItemText(1, _translate("MainWindow", "Ch 2"))
        self.HistChannel.setItemText(2, _translate("MainWindow", "Ch 3"))
        self.HistChannel.setItemText(3, _translate("MainWindow", "Ch 4"))
        self.FOVLabel.setText(_translate("MainWindow", "FOV"))
        self.NuclMaskCheckBox.setText(_translate("MainWindow", "Nuclei"))
        self.NucPreviewMethod.setItemText(0, _translate("MainWindow", "Boundary"))
        self.NucPreviewMethod.setItemText(1, _translate("MainWindow", "Area"))
        self.SpotsCheckBox.setText(_translate("MainWindow", "Spots"))
        self.SpotPreviewMethod.setItemText(0, _translate("MainWindow", "Dots"))
        self.SpotPreviewMethod.setItemText(1, _translate("MainWindow", "Cross"))
        self.CytoPreviewCheck.setText(_translate("MainWindow", "Cell"))
        self.CytoDisplayMethod.setItemText(0, _translate("MainWindow", "Boundary"))
        self.CytoDisplayMethod.setItemText(1, _translate("MainWindow", "Area"))
    
    def mousePressEvent(self, event):
        
        self.photoClicked.emit(self.mapToScene(event.pos()).toPoint())
        super(display, self).mousePressEvent(event)
        
    def wheelEvent(self, event):
        print('shit')
        if event.angleDelta().y() > 0:
            factor = 1.25
            self._zoom += 1
        else:                
            factor = 0.8
            self._zoom -= 1
        if self._zoom > 0:
            displaygui.ImageView.scale(factor, factor)
        elif self._zoom == 0:
            self.fitInView()
        else:
            self._zoom = 0